In [7]:
import pandas as pd
import numpy as np

In [9]:
df =pd.read_csv("Amazon Sale Report.csv")

C:\Users\sanju\AppData\Local\Temp\ipykernel_9080\3016405460.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df =pd.read_csv("Amazon Sale Report.csv")

In [10]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [11]:
df.shape

(128975, 24)

In [12]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [13]:
df.info

<bound method DataFrame.info of          index             Order ID      Date                        Status  \
0            0  405-8078784-5731545  04-30-22                     Cancelled
1            1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2            2  404-0687676-7273146  04-30-22                       Shipped
3            3  403-9615377-8133951  04-30-22                     Cancelled
4            4  407-1069790-7240320  04-30-22                       Shipped
...        ...                  ...       ...                           ...
128970  128970  406-6001380-7673107  05-31-22                       Shipped
128971  128971  402-9551604-7544318  05-31-22                       Shipped
128972  128972  407-9547469-3152358  05-31-22                       Shipped
128973  128973  402-6184140-0545956  05-31-22                       Shipped
128974  128974  408-7436540-8728312  05-31-22                       Shipped

       Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0        Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1        Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2          Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3        Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4          Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL
...           ...            ...                ...      ...              ...
128970     Amazon      Amazon.in          Expedited  JNE3697    JNE3697-KR-XL
128971     Amazon      Amazon.in          Expedited   SET401   SET401-KR-NP-M
128972     Amazon      Amazon.in          Expedited    J0157     J0157-DR-XXL
128973     Amazon      Amazon.in          Expedited    J0012     J0012-SKD-XS
128974     Amazon      Amazon.in          Expedited    J0003      J0003-SET-S

             Category  ... currency   Amount    ship-city    ship-state  \
0                 Set  ...      INR   647.62       MUMBAI   MAHARASHTRA
1               kurta  ...      INR   406.00    BENGALURU     KARNATAKA
2               kurta  ...      INR   329.00  NAVI MUMBAI   MAHARASHTRA
3       Western Dress  ...      INR   753.33   PUDUCHERRY    PUDUCHERRY
4                 Top  ...      INR   574.00      CHENNAI    TAMIL NADU
...               ...  ...      ...      ...          ...           ...
128970          kurta  ...      INR   517.00    HYDERABAD     TELANGANA
128971            Set  ...      INR   999.00     GURUGRAM       HARYANA
128972  Western Dress  ...      INR   690.00    HYDERABAD     TELANGANA
128973            Set  ...      INR  1199.00        Halol       Gujarat
128974            Set  ...      INR   696.00       Raipur  CHHATTISGARH

       ship-postal-code  ship-country  \
0              400081.0            IN
1              560085.0            IN
2              410210.0            IN
3              605008.0            IN
4              600073.0            IN
...                 ...           ...
128970         500013.0            IN
128971         122004.0            IN
128972         500049.0            IN
128973         389350.0            IN
128974         492014.0            IN

                                            promotion-ids    B2B  \
0                                                     NaN  False
1       Amazon PLCC Free-Financing Universal Merchant ...  False
2            IN Core Free Shipping 2015/04/08 23-48-5-108   True
3                                                     NaN  False
4                                                     NaN  False
...                                                   ...    ...
128970                                                NaN  False
128971       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128972                                                NaN  False
128973       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128974       IN Core Free Shipping 2015/04/08 23-48-5-108  False

        fulfilled-by Unnamed: 22
0          Easy Ship         NaN
1          Easy Ship         NaN
2                NaN         NaN
3          Easy Ship         NaN
4                NaN         NaN
...              ...         ...
128970           NaN       False
128971           NaN       False
128972           NaN       False
128973           NaN       False
128974           NaN       False

[128975 rows x 24 columns]>

In [14]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [17]:
df.drop(df.columns[-1],axis=1,inplace=True)

In [18]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='object')

In [19]:
df.shape

(128975, 23)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df['Amount'].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [25]:
df.loc[df['Amount'].isnull(),
'Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [28]:
df.loc[df['currency'].isnull(),
'Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [29]:
df['currency'].value_counts()

currency
INR    121180
Name: count, dtype: int64

In [30]:
df['currency'] =df['currency'].fillna('INR')

In [31]:
df['currency'].value_counts()

currency
INR    128975
Name: count, dtype: int64

In [32]:
df['currency'].isnull().sum()

np.int64(0)

In [33]:
df.loc[df["Amount"].isnull(),['Status','Qty','Category']]

           Status  Qty Category
8       Cancelled    0      Set
29      Cancelled    0    kurta
65      Cancelled    0    kurta
84      Cancelled    0    kurta
95      Cancelled    0    kurta
...           ...  ...      ...
128903  Cancelled    0    kurta
128907  Cancelled    0      Set
128908  Cancelled    0      Set
128958  Cancelled    0      Set
128967  Cancelled    0    kurta

[7795 rows x 3 columns]

In [34]:
df['Amount'] =df['Amount'].fillna(0)

In [36]:
df['Amount'].isnull().sum()

np.int64(0)

In [37]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency                  0
Amount                    0
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [38]:
df.loc[df['Courier Status'].isnull(),
'Status'].value_counts()

Status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [39]:
df['Courier Status'] =df['Courier Status'].fillna('Not Applicable')

In [40]:
df['Courier Status'].isnull().sum()

np.int64(0)

In [41]:
df.loc[df['ship-city'].isnull(),['ship-city','ship-state','ship-postal-code','ship-country']]

       ship-city ship-state  ship-postal-code ship-country
1871         NaN        NaN               NaN          NaN
1872         NaN        NaN               NaN          NaN
8752         NaN        NaN               NaN          NaN
11215        NaN        NaN               NaN          NaN
13252        NaN        NaN               NaN          NaN
15688        NaN        NaN               NaN          NaN
16787        NaN        NaN               NaN          NaN
18351        NaN        NaN               NaN          NaN
22930        NaN        NaN               NaN          NaN
24986        NaN        NaN               NaN          NaN
30379        NaN        NaN               NaN          NaN
37963        NaN        NaN               NaN          NaN
37964        NaN        NaN               NaN          NaN
60986        NaN        NaN               NaN          NaN
63040        NaN        NaN               NaN          NaN
73675        NaN        NaN               NaN          NaN
73746        NaN        NaN               NaN          NaN
73771        NaN        NaN               NaN          NaN
73772        NaN        NaN               NaN          NaN
73911        NaN        NaN               NaN          NaN
80011        NaN        NaN               NaN          NaN
80092        NaN        NaN               NaN          NaN
80455        NaN        NaN               NaN          NaN
84008        NaN        NaN               NaN          NaN
84757        NaN        NaN               NaN          NaN
104201       NaN        NaN               NaN          NaN
106498       NaN        NaN               NaN          NaN
124215       NaN        NaN               NaN          NaN
124357       NaN        NaN               NaN          NaN
124358       NaN        NaN               NaN          NaN
124359       NaN        NaN               NaN          NaN
125385       NaN        NaN               NaN          NaN
126620       NaN        NaN               NaN          NaN

In [42]:
df[['ship-city','ship-state','ship-postal-code','ship-country']] = df[['ship-city','ship-state','ship-postal-code','ship-country']].fillna('Unknown')

In [43]:
df[['ship-city','ship-state','ship-postal-code','ship-country']].isnull().sum()

ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
dtype: int64

In [44]:
df['promotion-ids'].isnull().sum()

np.int64(49153)

In [47]:
df['promotion-ids'] =df['promotion-ids'].fillna('No Promotion')

In [48]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='object')

In [49]:
df['promotion-ids'].isnull().sum()

np.int64(0)

In [50]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status            0
Qty                       0
currency                  0
Amount                    0
ship-city                 0
ship-state                0
ship-postal-code          0
ship-country              0
promotion-ids             0
B2B                       0
fulfilled-by          89698
dtype: int64

In [51]:
df.loc[df['fulfilled-by'].isnull(),'Status'].value_counts()

Status
Shipped      77804
Cancelled    11471
Pending        415
Shipping         8
Name: count, dtype: int64

In [52]:
df['fulfilled-by'] =df['fulfilled-by'].fillna('Unknown')

In [53]:
df.isnull().sum()

index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
promotion-ids         0
B2B                   0
fulfilled-by          0
dtype: int64

In [54]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code       object
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
dtype: object

In [56]:
df['Date'] =pd.to_datetime(df['Date'],format ='%m-%d-%y')

In [57]:
df['Date']

0        2022-04-30
1        2022-04-30
2        2022-04-30
3        2022-04-30
4        2022-04-30
            ...
128970   2022-05-31
128971   2022-05-31
128972   2022-05-31
128973   2022-05-31
128974   2022-05-31
Name: Date, Length: 128975, dtype: datetime64[ns]

In [58]:
df['Date'].dtype

dtype('<M8[ns]')

In [59]:
df['Date'].min(),df['Date'].max()

(Timestamp('2022-03-31 00:00:00'), Timestamp('2022-06-29 00:00:00'))

In [62]:
df['Month'] =df['Date'].dt.to_period('M')

In [63]:
df['Month']

0         2022-04
1         2022-04
2         2022-04
3         2022-04
4         2022-04
           ...
128970    2022-05
128971    2022-05
128972    2022-05
128973    2022-05
128974    2022-05
Name: Month, Length: 128975, dtype: period[M]

In [64]:
df[['Date','Month']].head()

        Date    Month
0 2022-04-30  2022-04
1 2022-04-30  2022-04
2 2022-04-30  2022-04
3 2022-04-30  2022-04
4 2022-04-30  2022-04

In [65]:
df['Qty'].describe()

count    128975.000000
mean          0.904431
std           0.313354
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          15.000000
Name: Qty, dtype: float64

In [66]:
df['Qty'].value_counts().sort_index()

Qty
0      12807
1     115780
2        341
3         32
4          9
5          2
8          1
9          1
13         1
15         1
Name: count, dtype: int64

In [67]:
df[df['Qty']<0]

Empty DataFrame
Columns: [index, Order ID, Date, Status, Fulfilment, Sales Channel , ship-service-level, Style, SKU, Category, Size, ASIN, Courier Status, Qty, currency, Amount, ship-city, ship-state, ship-postal-code, ship-country, promotion-ids, B2B, fulfilled-by, Month]
Index: []

[0 rows x 24 columns]

In [68]:
df['Amount'].describe()

count    128975.000000
mean        609.363662
std         313.347147
min           0.000000
25%         413.000000
50%         583.000000
75%         771.000000
max        5584.000000
Name: Amount, dtype: float64

In [69]:
df['Amount'].value_counts().sort_index().head()

Amount
0.00      10138
199.00        3
218.10        1
229.00       21
236.19        2
Name: count, dtype: int64

In [70]:
df['Status'].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [74]:
df['Amount'].sum()

np.float64(78592678.3)

In [73]:
df['Qty'].sum()

np.int64(116649)

In [76]:
df['Order ID'].nunique()

120378

In [77]:
df['SKU'].nunique()

7195

In [78]:
df['Category'].value_counts()

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [79]:
df['Category'].value_counts().head(10)

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [80]:
df.groupby('Category')['Amount'].sum().sort_values(ascending =False)

Category
Set              39204124.03
kurta            21299546.70
Western Dress    11216072.69
Top               5347792.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [90]:
df.columns.str.strip()

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Month', 'Sales'],
      dtype='object')

In [92]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Month',
 'Sales']

In [97]:
[c for c in df.columns if'Sales'in c or 'sales in c']

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Month',
 'Sales']

In [102]:
df.columns =[col.strip() for col in df.columns]

In [103]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Month', 'Sales'],
      dtype='object')

In [104]:
df['Sales Channel'].head()

0    Amazon.in
1    Amazon.in
2    Amazon.in
3    Amazon.in
4    Amazon.in
Name: Sales Channel, dtype: object

In [107]:
df.groupby('Sales Channel')['Amount'].agg('sum')

Sales Channel
Amazon.in     78592678.3
Non-Amazon           0.0
Name: Amount, dtype: float64

In [109]:
df['ship-state'].head()

0    MAHARASHTRA
1      KARNATAKA
2    MAHARASHTRA
3     PUDUCHERRY
4     TAMIL NADU
Name: ship-state, dtype: object

In [110]:
df.groupby('ship-state')['Amount'].agg('sum')

ship-state
ANDAMAN & NICOBAR      158723.62
ANDHRA PRADESH        3219831.72
APO                         0.00
AR                        493.00
ARUNACHAL PRADESH       95235.00
                         ...
goa                      2467.00
orissa                    597.00
punjab                   8622.00
rajasthan                3946.00
rajsthan                  521.00
Name: Amount, Length: 70, dtype: float64

In [113]:
df['ship-state'].head(10)

0      MAHARASHTRA
1        KARNATAKA
2      MAHARASHTRA
3       PUDUCHERRY
4       TAMIL NADU
5    UTTAR PRADESH
6       CHANDIGARH
7        TELANGANA
8        TELANGANA
9       TAMIL NADU
Name: ship-state, dtype: object

In [112]:
df.groupby('ship-state')['Amount'].agg(sum)

C:\Users\sanju\AppData\Local\Temp\ipykernel_9080\3058081546.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('ship-state')['Amount'].agg(sum)

ship-state
ANDAMAN & NICOBAR      158723.62
ANDHRA PRADESH        3219831.72
APO                         0.00
AR                        493.00
ARUNACHAL PRADESH       95235.00
                         ...
goa                      2467.00
orissa                    597.00
punjab                   8622.00
rajasthan                3946.00
rajsthan                  521.00
Name: Amount, Length: 70, dtype: float64

In [114]:
type(df)

pandas.core.frame.DataFrame

In [115]:
df.groupby('ship-state').size()

ship-state
ANDAMAN & NICOBAR      257
ANDHRA PRADESH        5430
APO                      1
AR                       1
ARUNACHAL PRADESH      141
                      ...
goa                      5
orissa                   1
punjab                  14
rajasthan                6
rajsthan                 1
Length: 70, dtype: int64

In [116]:
df.groupby('ship-state')['Amount'].sum()

ship-state
ANDAMAN & NICOBAR      158723.62
ANDHRA PRADESH        3219831.72
APO                         0.00
AR                        493.00
ARUNACHAL PRADESH       95235.00
                         ...
goa                      2467.00
orissa                    597.00
punjab                   8622.00
rajasthan                3946.00
rajsthan                  521.00
Name: Amount, Length: 70, dtype: float64

In [119]:
state_sales =df.groupby('ship-state')['Amount'].sum()

In [120]:
state_sales.nlargest(10)

ship-state
MAHARASHTRA       13335534.14
KARNATAKA         10481114.37
TELANGANA          6916615.65
UTTAR PRADESH      6816642.08
TAMIL NADU         6515650.11
DELHI              4235215.97
KERALA             3830227.58
WEST BENGAL        3507880.44
ANDHRA PRADESH     3219831.72
HARYANA            2882092.99
Name: Amount, dtype: float64

In [122]:
df['Status'].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [123]:
df['Courier Status'].value_counts()

Courier Status
Shipped           109487
Not Applicable      6872
Unshipped           6681
Cancelled           5935
Name: count, dtype: int64

In [124]:
sku_sales =df.groupby('SKU')['Amount'].sum()

In [125]:
sku_sales.nlargest(10)

SKU
J0230-SKD-M        527699.20
JNE3797-KR-L       524581.77
J0230-SKD-S        479937.14
JNE3797-KR-M       454290.16
JNE3797-KR-S       407302.57
JNE3797-KR-XL      332155.24
J0230-SKD-L        305616.95
JNE3797-KR-XS      303616.70
SET268-KR-NP-XL    284058.96
JNE3797-KR-XXXL    276375.80
Name: Amount, dtype: float64

In [126]:
df.groupby('Courier Status')['Amount'].agg('sum')

Courier Status
Cancelled                0.0
Not Applicable     3190172.3
Shipped           71058664.0
Unshipped          4343842.0
Name: Amount, dtype: float64

In [127]:
df.groupby('Fulfilment')['Amount'].agg(sum)

C:\Users\sanju\AppData\Local\Temp\ipykernel_9080\2359006258.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('Fulfilment')['Amount'].agg(sum)

Fulfilment
Amazon      54322151.0
Merchant    24270527.3
Name: Amount, dtype: float64

In [128]:
city_sales =df.groupby('ship-city')['Amount'].sum()

In [129]:
city_sales.nlargest(10)

ship-city
BENGALURU    6849664.99
HYDERABAD    4946032.82
MUMBAI       3704461.80
NEW DELHI    3613874.78
CHENNAI      3098745.74
PUNE         2338518.18
KOLKATA      1414978.87
GURUGRAM     1221618.74
THANE        1004355.29
LUCKNOW       933926.34
Name: Amount, dtype: float64

In [130]:
category_qty =df.groupby('Category')['Qty'].sum()

In [131]:
category_qty.nlargest(10)

Category
Set              45289
kurta            45045
Western Dress    13943
Top               9903
Ethnic Dress      1053
Blouse             863
Bottom             398
Saree              152
Dupatta              3
Name: Qty, dtype: int64

In [135]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Month',
 'Sales']

In [138]:
[col for col in df.columns if 'service' in col.lower()]

['ship-service-level']

In [139]:
service_level_sales =df.groupby('ship-service-level')['Amount'].agg(sum)

C:\Users\sanju\AppData\Local\Temp\ipykernel_9080\2558992960.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  service_level_sales =df.groupby('ship-service-level')['Amount'].agg(sum)

In [140]:
size_sales =df.groupby('Size')['Amount'].agg('sum')

In [141]:
size_sales.nlargest(10)

Size
M      13906754.37
L      13234886.19
XL     12464965.86
XXL    10636288.45
S      10629210.18
3XL     9157147.68
XS      7022375.20
6XL      576249.33
5XL      425156.63
4XL      334451.64
Name: Amount, dtype: float64

In [148]:
(df['Status'].eq('Cancelled').sum()/len(df))*100

np.float64(14.213607288234154)

In [157]:
[col for col in df.columns if'order'in col.lower()]

['Order ID']

In [159]:
df['Amount'].sum()/df['Order ID'].nunique()

np.float64(652.8824062536344)

In [160]:
monthly_orders =df.groupby('Month')['Order ID'].nunique()
monthly_orders

Month
2022-03      158
2022-04    45858
2022-05    39221
2022-06    35141
Freq: M, Name: Order ID, dtype: int64

In [161]:
status_sales =df.groupby('Status')['Amount'].sum()
status_sales

Status
Cancelled                         6919284.3
Pending                            430271.0
Pending - Waiting for Pick Up      192138.0
Shipped                          50324255.0
Shipped - Damaged                    1136.0
Shipped - Delivered to Buyer     18650815.0
Shipped - Lost in Transit            1997.0
Shipped - Out for Delivery          26971.0
Shipped - Picked Up                661252.0
Shipped - Rejected by Buyer          7295.0
Shipped - Returned to Seller      1269644.0
Shipped - Returning to Seller      107620.0
Shipping                                0.0
Name: Amount, dtype: float64

In [162]:
kpi_summary ={
    'Total Orders': df['Order ID'].nunique(),
    'Total Sales': df['Amount'].sum(),
    'Total Quantity': df['Qty'].sum(),
    'Cancelled Orders': df['Status'].eq('Cancelled').sum(),
    'Cancelled Rate(%)':(df['Status'].eq('Cancelled').sum()/len(df))*100,
    'Unique SKUs': df['SKU'].nunique()
}
kpi_summary

{'Total Orders': 120378,
 'Total Sales': np.float64(78592678.3),
 'Total Quantity': np.int64(116649),
 'Cancelled Orders': np.int64(18332),
 'Cancelled Rate(%)': np.float64(14.213607288234154),
 'Unique SKUs': 7195}

In [165]:
df.to_csv('Amazon_Ecommerce_Cleaned.csv',index=False)

In [166]:
import os
os.path.exists('Amazon_Ecommerce_Cleaned.csv')

True